[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm db:generate && pnpm build"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "pnpm start"

[env]
NODE_ENV = "production"
PORT = "3000" 